### ISSUE TITLE
On windows? + questions

### ISSUE THREAD

**Issue by APISeeker** [NavodPeiris/speechlib#17]
Hello
I was installing and I saw this:

GPU execution requires the following NVIDIA libraries to be installed:

cuBLAS for CUDA 11
cuDNN 8 for CUDA 11

But when I click on the links for (cuBLAS for CUDA 11), and go to windows links I shows this:

> The NVIDIA HPC SDK for Windows will be available at a later date.

![image](https://github.com/Navodplayer1/speechlib/assets/145594487/04ed201d-9f77-4eed-b14f-d2556fefd04c)

Can I install this anyway?
I am really interested.
2) Second question, why do we need to give ADMIN right to make it work?
3) Have you compared it to pyannote? Is it different? Better etc?

Thanks

**Comment by Navodplayer1** [comment]
1. I haven't tried installing CUDA toolkit as i don't have a GPU. However, I have provided a Colab notebook that installs cublas and you can run using Colab GPU. If you don't want GPU execution then you can just pip install and run on CPU. in that case you don't need to install cublas. 

 2. The speaker recognition function requires admin rights to access files.
 3. it uses pyannote for diarization. so it is same. only difference is, it does speaker recognition.

**Comment by APISeeker** [comment]
Hello,
I absolutely 100% no 100000% need GPU.  I can't wait for long to get results..
Unless you have a solution that uses multi cores of a single processor to make it faster ? (suggestion)

Ok thank you I will try the collab to see how it works.

I don't know yet how pyannote works yet, so I don't know very well the difference yet. I guess your solution is better because you can use "audio samples" to explain with precision which is which and who is who and avoid having mistakes.
