### ISSUE TITLE
Leave old branch without faster whisper for AMD,Intel and other users?

### ISSUE THREAD

**Issue by tomich** [NavodPeiris/speechlib#31]
With my AMD, Intel, raspberry pi GPUs I can use GPU accelerated whisper and GPU accelerated pyannote. In the specific case on AMD by using pytorch-rocm and setting whisper and pyannote to use cuda.

But I cannot use faster whisper because ctranslate2 does not work on AMD.

Could it be possible to have a branch without faster whisper for AMD (and other) users?

**Comment by NavodPeiris** [comment]
you can download version 1.0.7 which is before we added faster whisper.

```
pip install speechlib==1.0.7
```

usage of old API:

```
from speechlib import Transcriptor

file = "obama_zach.wav"
voices_folder = "voices"
language = "english"
log_folder = "logs"
modelSize = "medium"

transcriptor = Transcriptor(file, log_folder, language, modelSize, voices_folder)

res = transcriptor.transcribe()

print("res", res)
```

note: back then we didn't have quantization and language is specified by its name and not using the language code.

**Comment by tomich** [comment]
Thankss
