### ISSUE TITLE
faster-whisper==1.0.1 transcription creates duplicate sentences.

### ISSUE THREAD

**Issue by AnshumanParidaIL** [NavodPeiris/speechlib#32]
Transcribing with faster-whisper==1.0.1 produces duplicate sentences:
![image](https://github.com/NavodPeiris/speechlib/assets/159989966/8eabd78d-6770-4889-8074-fc558770ef83)

This issue is solved by upgrading `faster-whisper` to 1.0.2 as discussed [here ](https://github.com/SYSTRAN/faster-whisper/issues/716)in the official `SYSTRAN/faster-whisper` repo.

**Comment by NavodPeiris** [comment]
in latests speechlib==1.0.15 version, this is fixed and now using faster-whisper==1.0.2. 
We were using faster-whisper==0.10.1

Thank you for the heads up!!

**Comment by AnshumanParidaIL** [comment]
Thank you for the clarification.
